services:
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    entrypoint: /entrypoint.sh
    command: python manage.py runserver_plus --cert-file certificate/nginx-selfsigned.crt --key-file certificate/nginx-selfsigned.key 0.0.0.0:8000
    depends_on:
        - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=koordapp
    ports:
      - "5432:5432"
volumes:
    postgres_data: