# Generated by Django 4.2.5 on 2024-02-07 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='mensa_feedback',
            field=models.BooleanField(default=False),
        ),
    ]
