# Generated by Django 4.2.5 on 2025-01-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='raum',
            name='color',
            field=models.CharField(default='#FFFFFF', help_text='Hex color code, e.g., #FFFFFF for white', max_length=7),
        ),
        migrations.AddField(
            model_name='raum',
            name='kategorie',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='raum',
            name='geschoss',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='raum',
            name='raum_nr',
            field=models.CharField(max_length=15),
        ),
    ]
