# Generated by Django 4.2.5 on 2024-02-09 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_personal_vertretung_remove_gruppe_gruppen_leiter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schueler',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.nutzer'),
        ),
    ]
