# Generated by Django 4.2.5 on 2024-02-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_schueler_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal',
            name='vertretung',
        ),
        migrations.AddField(
            model_name='gruppe',
            name='vertreter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vertretende_gruppen', to='main_app.personal'),
        ),
        migrations.AlterField(
            model_name='gruppe',
            name='raum',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leitende_gruppen', to='main_app.raum'),
        ),
    ]
