# Generated by Django 4.2.5 on 2024-02-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feedback_mensa_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='vertretung',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='gruppe',
            name='gruppen_leiter',
        ),
        migrations.AddField(
            model_name='gruppe',
            name='gruppen_leiter',
            field=models.ManyToManyField(to='main_app.personal'),
        ),
    ]
